### ISSUE TITLE
Allow TevIpc to be disposed even after connection failure

### ISSUE THREAD

**Issue by PearCoding** [pgrit/SimpleImageIO#3]
The following lines:
https://github.com/pgrit/SimpleImageIO/blob/b9bc75607e374468c8304c22f0488e7d3e70d808/SimpleImageIO/TevIpc.cs#L343-L344
have to be changed to 
```
            stream?.Dispose();
            client?.Dispose();
```
to allow the dispose of the TevIpc class after the constructor fails to connect to tev.

Another feature would be to allow to query the state if the constructor was successful or not. Maybe a property `Connected` would be nice.

**Comment by pgrit** [comment]
Wouldn't it be a better idea to simply throw an exception in the constructor and not even have a valid TevIpc object if the connection failed?

**Comment by pgrit** [comment]
Can you check if https://github.com/pgrit/SimpleImageIO/pull/4 works as intended?

**Comment by PearCoding** [comment]
> 
> 
> Wouldn't it be a better idea to simply throw an exception in the constructor and not even have a valid TevIpc object if the connection failed?

I agree. The existence of TevIpc is only valid if there is a connection. In the end it depends on the design principles of SimpleImageIO.

**Comment by PearCoding** [comment]
> 
> 
> Can you check if #4 works as intended?

Will give it a try
